#!/usr/bin/env ruby

require "date"
require "json"

download_path = "#{ENV["HOME"]}/Downloads"
list = Dir.children(download_path).select { |f|
  f.match(/,.+_(.{5})\.csv/)
}.group_by { |f|
  f.split(",").first
}.map { |g, files|
  files.sort_by { |f| File.ctime("#{download_path}/#{f}") }.last
}

def build_bars(lines)
  lines.map { |line|
    timestamp, open, high, low, close, volume, *_rest = line.split(",")

    {
      timestamp: timestamp.to_i,
      open: open.to_f,
      high: high.to_f,
      low: low.to_f,
      close: close.to_f,
      volume: volume.to_i
    }
  }
end

#  .match(/.+_(.+?)\, (.+?)_/)

list.each do |f|
  path = "#{download_path}/#{f}"
  bars = build_bars(File.readlines(path)[1..-1])

  m = f.match(/\w_(.+?)\, (.+?)_/)
  symbol = m[1]
  timeframe = m[2]

  system("mkdir -p data/1 data/5 data/15")

  output_path = "data/#{timeframe}/#{symbol}.json"
  puts "Writing #{output_path}"
  File.write(output_path, bars.to_json)
end
